[project]
name = "spark-poc-project"
version = "0.1.0"
description = "A professional Apache Spark Proof of Concept"
authors = [
    { name = "Your Name", email = "you@example.com" }
]
dependencies = [
    "pyspark==4.1.1",
]
requires-python = ">=3.11,<3.12"

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff>=0.15.11",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
