[project]
name = "spark-poc-project"
version = "0.1.0"
description = "A professional Apache Spark Proof of Concept"
authors = [
    { name = "Gryphus Lab", email = "dev@gryphus-lab.dev" }
]
dependencies = [
    "pyspark==4.0.4",
]
requires-python = ">=3.10,<3.13"

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff>=0.15.11",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
